### ISSUE TITLE
Generated names of Persons will sometimes be blank

### ISSUE THREAD

**Issue by Poyo-SSB** [LudicrousJimblemen/DestroyEverythingGame#1]
Relevant code from [Person.cs](https://github.com/LudicrousJimblemen/DestroyEverythingGame/blob/9080493c1dba93a101a0f3c045b307e355400079/Assets/Scripts/Person.cs#L184-L208)

	string consonants = "bbbbbbbbbbbbbbbbbcdfghjklmnpppppppppppppppppqrssstvwxzzz";
	string vowels = "aaeeiioooooooouuuuuuuuy";
	
	int type = Mathf.RoundToInt(UnityEngine.Random.Range(0, 1));
	
	identity.Name = String.Empty;
	
	for (int i = 0; i < 14; i++) {
		if (i != 7) {
			float chance = UnityEngine.Random.value;
			if (type == 0) {
				identity.Name += consonants.GetRandom();
				if (chance <= 0.5) {
					type = 1;
				}
			} else {
				identity.Name += vowels.GetRandom();
				if (chance <= 0.6) {
					type = 0;
				}
			}
		} else {
			identity.Name += " ";
		}
	}

**Comment by Avekeez** [comment]
I refuse to perform this task???

Do Not Make me Do this Tsak??????

Greetings from Germany, Jim
